language: node_js

node_js:
  - 'stable'
  - '8'

script:
  - npm run test

cache:
  directories:
    - node_modules

deploy:
  provider: heroku
  api_key:
    secure: "f2f36623-c5ad-454f-a5c4-3950ffff7c17"