language: node_js
node_js:
  - "8"
  - "11"
scripts:
  - npm install
  - npm test
deploy:
  provider: heroku
  api_key: 
    secure: dce6678b-128e-42ba-ad41-9ebe5562131f
  app: travis-ale
  on: ejemplo 